services:
  # -----------------------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL
  # -----------------------------------------------------------
  db-servicio:
    image: mysql:8.0
    container_name: mysql_servidor
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: universidad_backend
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3307:3307" # Mapea el puerto 3307 de tu PC al 3306 interno del contenedor
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_db:/var/lib/mysql

  # -----------------------------------------------------------
  # CONTENEDOR 2: EL ENTORNO DE TRABAJO JAVA/SPRING BOOT
  # -----------------------------------------------------------
  workspace-java:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_programacion
    ports:
      - "8081:8081"
    depends_on:
      - db-servicio
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./codigo-fuente:/app
    working_dir: /app

networks:
  red_interna_proyecto:

volumes:
  persistencia_db: