spring.application.name=backend-hotel-registro
# Puerto único para este microservicio de registro de usuarios/clientes
server.port=8081


# CONFIGURACIÓN OPENFEIGN (Sincronizada exactamente con tu HabitacionesClient)
# En Docker, buscará la variable de entorno HABITACIONES_URL. Si no existe, usará habitaciones_servidor:8080
microservicio.habitaciones.url=${HABITACIONES_URL:http://habitaciones_servidor:8080}

# Tiempos de espera para evitar que tu app se quede colgada si el otro servicio cae
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# CONEXIÓN A BASE DE DATOS (Apuntando al contenedor MySQL del Docker Compose)
spring.datasource.url=jdbc:mysql://mysql_servidor:3306/universidad_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE Y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LOGGING (Ideal para ver en consola los requests y responses de Feign)
logging.level.cl.duoc.backend_hotel_registro=INFO
logging.level.org.springframework.cloud.openfeign=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html